package Ventanas;

import Clases.conexion_mysql;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


public class Consulta_general extends javax.swing.JFrame {
         conexion_mysql bd = new conexion_mysql();
         Connection sb = bd.Conectar();
   
    public Consulta_general() {
         initComponents();
         fondo();
         txtidentificacion.setEnabled(false);
         cargarpersonas();
    }
        
    
    public void fondo(){
        //pantalla centrada
        setLocationRelativeTo(null);
        //sin modificarse
        setResizable(false);
        //Titulo
        setTitle("CONSULTAR");
        /*Icono de ventana
        setIconImage(new ImageIcon(get.class).getResource("/Fondos/"));*/
        //Fondo
        ((JPanel)getContentPane()).setOpaque(false); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Fondos/fondo-azul.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno); getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }
    
    public void cargarpersonas(){
     DefaultTableModel modelo= new DefaultTableModel();
     String []Titulos ={"CEDULA","NOMBRES","APELLIDOS","EDAD","GENERO","EMAIL","DIRECCION","TELEFONO","STATUS"};
     modelo.setColumnIdentifiers(Titulos); 
     this.tbpersona.setModel(modelo);
        try {
            String ConsultaSQL="SELECT * FROM persona";
            String []registros= new String[9];
            Statement st = sb.createStatement();
            ResultSet rs = st.executeQuery(ConsultaSQL);
            while(rs.next())
            {
                registros[0]=rs.getString("identification");
                registros[1]=rs.getString("name");
                registros[2]=rs.getString("last_name");  
                registros[3]=rs.getString("age");
                registros[4]=rs.getString("genere");
                registros[5]=rs.getString("email");
                registros[6]=rs.getString("address");
                registros[7]=rs.getString("cellphone");
                registros[8]=rs.getString("status");
                modelo.addRow(registros);
            }
            tbpersona.setModel(modelo);
            txtcan.setText(""+tbpersona.getRowCount());
            
        } catch (SQLException ex) {
            Logger.getLogger(Consulta_general.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        checkall = new javax.swing.JRadioButton();
        checktipousuario = new javax.swing.JRadioButton();
        checkbuscar = new javax.swing.JRadioButton();
        txtidentificacion = new javax.swing.JTextField();
        tipo_usuario = new javax.swing.JComboBox<>();
        butconsultat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        butsalir = new javax.swing.JButton();
        butreports = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        txtcan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbpersona = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONSULTAR PERSONAS ");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(checkall);
        checkall.setSelected(true);
        checkall.setText("Mostrar Todos los Registrados");
        checkall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkallActionPerformed(evt);
            }
        });

        buttonGroup1.add(checktipousuario);
        checktipousuario.setText("Mostrar Por Tipo de Usuario:");
        checktipousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checktipousuarioActionPerformed(evt);
            }
        });

        buttonGroup1.add(checkbuscar);
        checkbuscar.setText("Cedula de Identidad:");
        checkbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbuscarActionPerformed(evt);
            }
        });

        txtidentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidentificacionActionPerformed(evt);
            }
        });
        txtidentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidentificacionKeyTyped(evt);
            }
        });

        tipo_usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Administrador", "Docente", "Estudiante" }));
        tipo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_usuarioActionPerformed(evt);
            }
        });

        butconsultat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/13.png"))); // NOI18N
        butconsultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butconsultatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(checkbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(checktipousuario)
                        .addGap(26, 26, 26)
                        .addComponent(tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(butconsultat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkall)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(checkall)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checktipousuario)
                            .addComponent(tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkbuscar)
                            .addComponent(txtidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 48, Short.MAX_VALUE)
                        .addComponent(butconsultat, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        butsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/14.png"))); // NOI18N
        butsalir.setText("SALIR");
        butsalir.setToolTipText("");
        butsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        butsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsalirActionPerformed(evt);
            }
        });

        butreports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/6.png"))); // NOI18N
        butreports.setText("REPORTE");
        butreports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butreportsActionPerformed(evt);
            }
        });

        jLabel1.setText("CANTIDAD DE REGISTROS:");

        txtcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butreports)
                .addGap(18, 18, 18)
                .addComponent(butsalir)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butsalir)
                    .addComponent(butreports, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtcan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tbpersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbpersona);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Mini_logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checktipousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checktipousuarioActionPerformed
       if(checktipousuario.isSelected()==true)
    {
        tipo_usuario.setSelectedItem(0);
        tipo_usuario.setEnabled(true);
        txtidentificacion.setEnabled(false);
        txtidentificacion.setText("");
    }
        
    }//GEN-LAST:event_checktipousuarioActionPerformed

    private void checkbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbuscarActionPerformed
        if(checkbuscar.isSelected()==true){
         tipo_usuario.setSelectedIndex(0);
         tipo_usuario.setEnabled(false);
         txtidentificacion.setEnabled(true);
         txtidentificacion.requestFocus();
        }
       
    }//GEN-LAST:event_checkbuscarActionPerformed

    private void txtidentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidentificacionActionPerformed

    private void tipo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_usuarioActionPerformed
     
    }//GEN-LAST:event_tipo_usuarioActionPerformed

    private void butconsultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butconsultatActionPerformed
   String tipo=tipo_usuario.getSelectedItem().toString();
        String ci=txtidentificacion.getText();
        int aux=0;
        if(tipo=="Administrador" && checktipousuario.isSelected()==true){
            aux=1;
            }else if(tipo=="Docente" && checktipousuario.isSelected()==true){
                aux=2;   
                }else if(tipo=="Estudiante" && checktipousuario.isSelected()==true){
                    aux=3;
                        }else if(tipo=="Seleccione" && checktipousuario.isSelected()==true){
                            JOptionPane.showMessageDialog(null,"Seleccione una opcion valida");
                        }
        
        if(checktipousuario.isSelected()==true){
            
            DefaultTableModel modelo= new DefaultTableModel();
            String []Titulos ={"CEDULA","NOMBRES","APELLIDOS","EDAD","GENERO","EMAIL","DIRECCION","TELEFONO","STATUS","TIPO USUARIO"};
            modelo.setColumnIdentifiers(Titulos); 
            this.tbpersona.setModel(modelo);
        try {
            String ConsultaSQL="SELECT * FROM persona WHERE tipo_usuario='"+aux+"'";
            //String ConsultaSQL="SELECT persona.*,category_user.* FROM persona JOIN category_user ON (persona.tipo_usuario=category_user.id_category_user) WHERE tipo_usuario='"+aux+"'";
            String []registros= new String[10];
            Statement st = sb.createStatement();
            ResultSet rs = st.executeQuery(ConsultaSQL);
            while(rs.next())
            {
                registros[0]=rs.getString("identification");
                registros[1]=rs.getString("name");
                registros[2]=rs.getString("last_name");  
                registros[3]=rs.getString("age");
                registros[4]=rs.getString("genere");
                registros[5]=rs.getString("email");
                registros[6]=rs.getString("address");
                registros[7]=rs.getString("cellphone");
                registros[8]=rs.getString("status");
                registros[9]=rs.getString("tipo_usuario");
                modelo.addRow(registros);
            }
            
            tbpersona.setModel(modelo);
            txtcan.setText(""+tbpersona.getRowCount());
            
            } catch (SQLException ex) {
                Logger.getLogger(Consulta_general.class.getName()).log(Level.SEVERE, null, ex);
            } 
      }
        
        if(checkbuscar.isSelected()==true){
           
            DefaultTableModel modelo= new DefaultTableModel();
            String []Titulos ={"CEDULA","NOMBRES","APELLIDOS","EDAD","GENERO","EMAIL","DIRECCION","TELEFONO","STATUS"};
            modelo.setColumnIdentifiers(Titulos); 
            this.tbpersona.setModel(modelo);
            try {
            String ConsultaSQL="SELECT * FROM persona WHERE identification='"+ci+"'";
            String []registros= new String[9];
            Statement st = sb.createStatement();
            ResultSet rs = st.executeQuery(ConsultaSQL);
            //if(rs!= null){ 
            while(rs.next()){
                registros[0]=rs.getString("identification");
                registros[1]=rs.getString("name");
                registros[2]=rs.getString("last_name");  
                registros[3]=rs.getString("age");
                registros[4]=rs.getString("genere");
                registros[5]=rs.getString("email");
                registros[6]=rs.getString("address");
                registros[7]=rs.getString("cellphone");
                registros[8]=rs.getString("status");
                modelo.addRow(registros);
            }
            //}else{JOptionPane.showMessageDialog(null,"CEDULA INGRESADA NO SE ENCUENTRA REGISTRADA");}
            tbpersona.setModel(modelo);
            txtcan.setText(""+tbpersona.getRowCount());
            
            }catch (SQLException ex) {
            Logger.getLogger(Consulta_general.class.getName()).log(Level.SEVERE, null, ex);
            }
      }
        
        if(checkall.isSelected()==true){
            cargarpersonas();
        }            
    }//GEN-LAST:event_butconsultatActionPerformed

    private void butsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsalirActionPerformed
        // TODO add your handling code here:
        Administrador n = new Administrador();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_butsalirActionPerformed

    private void butreportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butreportsActionPerformed

       JasperReport jr=null;
        String archivo= System.getProperty("user.dir")+"//report1.jasper";
          // Map parametro = new HashMap();
          // parametro.clear();
           
          // parametro.put("parameter1", txtnumero.getText());
          
         try {
            //jr= JasperCompileManager.compileReport(archivo);
            jr=(JasperReport) JRLoader.loadObject(archivo);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, ex,"IMPOSIBLE MOSTRAR REPORTE...",JOptionPane.ERROR_MESSAGE);
      // Logger.getLogger(Bitacora.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            conexion_mysql con=new conexion_mysql();
            JasperPrint jp = JasperFillManager.fillReport(jr,null,con.Conectar());
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setTitle("Reporte");
            jv.setExtendedState(Frame.MAXIMIZED_BOTH);
            jv.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, ex,"IMPOSIBLE MOSTRAR REPORTE...",JOptionPane.ERROR_MESSAGE);
           // Logger.getLogger(Bitacora.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_butreportsActionPerformed

    private void txtcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcanActionPerformed

    private void txtidentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidentificacionKeyTyped
       char ced=evt.getKeyChar();
        if(ced<'0'||ced>'9'){
            evt.consume();
        }
    }//GEN-LAST:event_txtidentificacionKeyTyped

    private void checkallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkallActionPerformed
        cargarpersonas();
        tipo_usuario.setSelectedIndex(0);
        tipo_usuario.setEnabled(false);
        txtidentificacion.setText("");
        txtidentificacion.setEnabled(false);
    }//GEN-LAST:event_checkallActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butconsultat;
    private javax.swing.JToggleButton butreports;
    private javax.swing.JButton butsalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton checkall;
    private javax.swing.JRadioButton checkbuscar;
    private javax.swing.JRadioButton checktipousuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbpersona;
    private javax.swing.JComboBox<String> tipo_usuario;
    private javax.swing.JTextField txtcan;
    private javax.swing.JTextField txtidentificacion;
    // End of variables declaration//GEN-END:variables
}
